# Custom workflow for the Rain World modding wiki update project

name: wiki-workflow

on: [push, workflow_dispatch]

jobs:
  add-article-css:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: generate html pages
        working-directory: ./.github/workflows
        run: |
          python3 -m pip install mistune==2.0.0a6
          python3 -m pip install beautifulsoup4
          python3 ./.github/workflows/html_converter.py
          
      - name: commit changes
        uses: EndBug/add-and-commit@v6
        with:
          message: 'Automatically added resource links (GitHub Action)'
          add: pages
